### ISSUE TITLE
Display Results from Backend

### ISSUE THREAD

**Issue by SandervanDeurzenStudent** [LaurenzPoll/DPP#29]
**Description**: Implement a mechanism to dynamically load the quick scan results from the backend and display them on the results page. 

**Subtasks**: 

- [x] Implement the API call to retrieve results from the backend. 
- [x] Process and format the results for clear display. 
- [x] Implement error handling if the backend fails to return data.
