### ISSUE TITLE
Frontend - Quick Scan Results Page Creation

### ISSUE THREAD

**Issue by SandervanDeurzenStudent** [LaurenzPoll/DPP#30]
**Description**: Develop a page for displaying the results of the quick scan retrieved from the backend. 

**Subtasks:** 

- [x] Create the layout for the results page. 
- [x] Ensure that the results are clearly displayed, with graphical elements if needed for clarity. 
- [x] Test the results page with sample data.
