### ISSUE TITLE
Create Fields for Form Page

### ISSUE THREAD

**Issue by SandervanDeurzenStudent** [LaurenzPoll/DPP#31]
**Description**: Add all required input fields to the form page to collect the necessary data for the quick scan. 

**Subtasks**: 

- [ ] Specify and add the required fields. 
- [ ] Set up input validation for each field (e.g., required fields, numeric input, etc.). 
- [ ] Ensure that all input data is correctly sent to the backend. 

Constrains: 

-         10 Fields. 
-         Tooltip function per field. 
-         Fill in the text later.
